'use client'
import { useState } from "react";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillInstagram,
         AiFillLinkedin,
         AiFillGithub 
        } from "react-icons/ai";
import { FaTelegram } from "react-icons/fa";
import Image from "next/image";
import me from "../../public/me-removebg.png"
import design from "../../public/design.png";
import web from "../../public/web.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  
  return (
    <div className={darkMode ? "dark": "" }>
    <Head>
      <title>Sobirkhon Alimov Portofolio</title>
      <meta name="description" content="Generated by creator"></meta>
    </Head>
    <main className=" text-black px-10 md:px-20 lg:px-40 dark:bg-gray-900">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between ">
          <h1 className=" text-xl font-burtons text-gray-600">Developer By Alimov</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-gray-700"/>
              </li>
            <li>
              <a className="bg-gradient-to-r from-teal-600 to-cyan-500 text-white px-4 py-2 rounded-xl ml-8" href="#">Resume</a>
              </li>
          </ul>
        </nav>

        <div className=" text-center p-10">
           <h2 className=" text-5xl py-2 text-teal-500 font-medium md:text-6xl">Sobirkhon Alimov</h2>
           <h3 className="text-2xl py-2 text-gray-600">Software Developer</h3>
           <p className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl mx-auto">Dedicated to lifelong learning, constantly seeking to expand knowledge and stay abreast of the latest developments in software development.</p>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
          <a href="https://github.com/alimoff"><AiFillGithub /> </a>
          <a href="https://www.linkedin.com/in/alimoff"><AiFillLinkedin /> </a>
          <a href="https://www.instagram.com/alimoff.io"><AiFillInstagram /> </a>
          <a href="https://www.t.me/alimoffsk"><FaTelegram /> </a>
        </div>
        <div className="relative flex justify-center mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
          <Image className=" size-60" src={me} layout={"fill"} objectFit="cover" alt={""}/>
        </div>
      </section>

      <section>
        <div className="text-center">
          <h3 className="text-3xl py-10 text-gray-700">Services I Offer</h3>
          <p className="text-md py-2 leading-8 text-gray-600">
            My coding journey with <span className="text-teal-500">React</span> and <span className="text-teal-500">Tailwind CSS</span> has been dynamic, empowering me to create sophisticated user interfaces with modular components and streamlined styling. Integrating these technologies alongside <span className="text-teal-500">Node.js</span> and <span className="text-teal-500">Express.js</span> has facilitated the development of robust full-stack web applications.
          </p>
          <p className="text-md py-2 leading-8 text-gray-500">
            I offer from a wide range of services, including brand design, programming and teaching
          </p>
        </div>

        <div>
          <div className="text-center items-center shadow-lg p-10 rounded-xl my-10">
            <Image src={web} width={100} height={100} alt={""}/>
            <h3 className="text-lg font-medium pt-8 pb-2 text-gray-600">Multi-Functional Websites</h3>
            <p className="py-2 text-gray-700">Creating multi-functional websites using complex logic.</p>
          <h4 className="py-4 text-teal-600"> Tools To Use</h4>
          <p className="text-gray-700 py-1">Python</p>
          <p className="text-gray-700 py-1">Node.js</p>
          <p className="text-gray-700 py-1">React.js</p>
          </div>

          <div className="text-center shadow-lg p-10 rounded-xl my-10 ">
            <Image src={design} width={100} height={100} alt={""}/>
            <h3 className="text-lg font-medium pt-8 pb-2 text-gray-600">Beautiful Designs</h3>
            <p className="py-2 text-gray-700">Creating elegant designs suited for your needs following core design theory </p>
          <h4 className="py-4 text-teal-600">Design Tools To Use</h4>
          <p className="text-gray-700 py-1">Photoshop</p>
          <p className="text-gray-700 py-1">Illustrator</p>
          <p className="text-gray-700 py-1">Figma</p>
          </div>
          <h1 className="text-center text-lg px-10 my-10 rounded-xl text-gray-600">Portofolio</h1>
         {/*For portofolio Projects*/}
         <p className="text-center py-2 text-gray-700">Since I started my journey as a <span className="text-teal-500">developer</span> and <span className="text-teal-500">designer</span>, I have done <span className="text-teal-500">remote</span> and <span className="text-teal-500">from office</span> with talented people to create digital products for both business and consumer use </p>
         <p className=" text-center py-2 leading-8 text-gray-600">I offer from wide range of services, including brand design, programming and teaching</p>
          <div>

          </div>
        </div>
      </section>
    </main>
    </div>
  );
}